title: Thales Galter
subtitle: Desenvolvedor Backend | C# | AWS | Node.js
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://tgalter.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Sobre Mim
      url: /about
    - text: Contato
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: foto.jpg
author: Thales Galter
author_bio: Sou desenvolvedor backend especializado em .NET e AWS, com mais de 15 anos de experiência em desenvolvimento de sistemas escaláveis, arquitetura serverless e integrações robustas. Tenho atuação sólida em ambientes financeiros e também em soluções envolvendo mensageria, APIs e automações com IA.
author_email: "thales.galter@gmail.com"
author_location: Caçapava, SP
author_website_url: "https://www.linkedin.com/in/thales-galter/"
typewrite-text: Desenvolvedor de Software | .Net Core | AWS | Nodejs | Angular | HTML5 | Splunk | SQL Server | Docker | CSS | JavaScript | Redis | REST API | Microservices | CI/CD | Agile/Scrum | TDD/BDD | Git/GitHub
typewrite-text2: Backend robusto, arquitetura cloud e integrações inteligentes
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img


#Certificates
certificates:
            - company_name: AWS Certified Solutions Architect – Associate
              company_logo: aws1.png
              company_url: https://www.credly.com/badges/42c1cbec-7b57-49fd-85ad-90ee1e749fb4/public_url
              description: Os profissionais que obtêm esta certificação possuem um conhecimento abrangente dos serviços e tecnologias AWS. Eles demonstraram a capacidade de criar soluções seguras e robustas usando princípios de design arquitetônico baseados nos requisitos do cliente. Os detentores deste selo são capazes de projetar estrategicamente sistemas distribuídos bem arquitetados, que são escaláveis, resilientes, eficientes e tolerantes a falhas.
              visibility: true
            - company_name: Exam 483 Programming in C#
              company_logo: m.png
              company_url: https://www.credly.com/badges/dd7e66e9-4e95-4d29-a9b9-1841ab7d00f0/linked_i
              description: A aprovação no Exame 483- Programação em C# valida a capacidade do candidato de gerenciar o fluxo do programa, criar e usar tipos, depurar aplicativos e implementar segurança, bem como implementar acesso a dados.
              visibility: true

# Experiences
author_work_experiences:
            - company_name: Itaú Unibanco
              company_logo: itau.png
              company_url: https://www.itau.com.br/
              designation: Tech Lead
              description: Vários projetos de alta escala, com foco em arquitetura e liderança de equipes.
              visibility: true
            - company_name: Sofhar
              company_logo: sofhar_logo.jpg
              company_url: https://www.linkedin.com/company/sofhar/
              designation: Desenvolvedor Full Stack
              description:  Essa é a SOFHAR. Comprometida em entregar as melhores soluções de Tecnologia da Informação e Comunicação para empresa públicas e privadas.
              visibility: true
            - company_name: G&P
              company_logo: gp.png
              company_url: https://www.gpnet.com.br/
              designation: Desenvolvedor Full Stack
              description: A G&P é uma empresa que atua há 35 anos no setor de Tecnologia da Informação e estamos presentes nas principais capitais do Brasil.
              visibility: true
            - company_name: ENVVIO
              company_logo: envvio.png
              company_url: https://www.envvio.com/pt/inicio/
              designation: Desenvolvedor Full Stack
              description: Envvio cria produtos e soluções de internet que aproximam empresas de seus clientes de forma otimizada e interativa.
              visibility: true

# Education
author_education_details:
              - college_logo: ibta.png
                college_name: Veris IBTA
                college_url: https://pt.wikipedia.org/wiki/Instituto_Brasileiro_de_Tecnologia_Avan%C3%A7ada
                college_degree: Sistemas
                description: Graduação em tecnoligia da informação.
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: ion.png
                project_title: ION – Aplicativo de Investimentos (Itaú)
                project_description: Desenvolvimento backend para o app de investimentos do banco Itaú. Atuando na construção de APIs escaláveis, arquitetura serverless e integrações com múltiplos sistemas internos do banco. Foco em resolver desafios de latência, garantindo alta performance e resiliência. Stack composta por AWS (Lambda, API Gateway, Fargate, CloudWatch), .NET Core, Redis, Terraform e Datadog.
                project_url: https://www.ion.itau/
                visibility: true
              - project_thumbnail: image.png
                project_title: Carnidals – Sistema de Viagens Corporativas
                project_description: Desenvolvimento de plataforma para gestão de viagens corporativas, funcionando como um “Decolar” para empresas. Sistema completo com emissão de passagens, reservas e controle de viagens. Backend em .NET MVC, frontend com jQuery, HTML5 e CSS3, integração via APIs REST e banco SQL Server.
                project_url: https://www.envvio.com/pt/cardinals/
                visibility: true
              - project_thumbnail: secretary.png
                project_title: SofIA Secretária – Automação de Agendamentos com IA
                project_description: Secretária eletrônica inteligente desenvolvida para clínicas, barbearias e pequenos negócios. Gerencia agendamentos, confirmações e lembretes via WhatsApp, com integração ao Google Calendar e suporte a IA generativa. Projeto desenvolvido em Node.js, com containers Docker, Redis, WhatsAppWeb.js e integração com a Gemini AI API. O maior desafio foi construir prompts eficientes e selecionar o modelo de IA ideal para simular uma secretária humana com respostas naturais.
                project_url: /secretaria
                visibility: true

# social links
#twitter_username: xplor4r
github_username:  TGalter
#instagram_username: xplor4r
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: thalesgalter

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: thales.galter@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_certificates: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin 

# Jekyll Admin Config
# jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  # homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
